# # build environment
# FROM node:12.2.0-alpine as build
# WORKDIR /app

# ENV PATH /app/node_modules/.bin:$PATH
# ENV REACT_APP_OBRAS_API_URL  http://localhost/
# ENV REACT_APP_RATINGS_API_URL  http://localhost/

# COPY package.json /app/package.json
# RUN npm install --silent
# RUN npm install react-scripts@3.0.1 -g --silent
# COPY . /app
# RUN npm run build

# production environment
# FROM nginx:1.16.0-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]



# production environment
FROM nginx:1.16.0-alpine

COPY ./build /usr/share/nginx/html
ENV REACT_APP_OBRAS_API_URL  http://localhost/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]