#!/bin/sh -eu
if [ -z "${REACT_APP_OBRAS_API_URL}" ]; then
    REACT_APP_OBRAS_API_URL_JSON=undefined
else
    REACT_APP_OBRAS_API_URL_JSON=$REACT_APP_OBRAS_API_URL
fi
if [ -z "${REACT_APP_RATINGS_API_URL:-}" ]; then
    REACT_APP_RATINGS_API_URL_JSON=undefined
else
    REACT_APP_RATINGS_API_URL_JSON=$REACT_APP_RATINGS_API_URL
fi

cat <<EOF
window.REACT_APP_OBRAS_API_URL = '${REACT_APP_OBRAS_API_URL_JSON}';
window.REACT_APP_RATINGS_API_URL = '${REACT_APP_RATINGS_API_URL_JSON}';
EOF